### ISSUE TITLE
Fix spelling mistake in some sequences

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-import-pipeline#119]
Some snoRNAs are called `Homo sapians` should be `Homo sapiens`. This is an issue from the providing database so we need to fix it when importing. We can also fix it in the database if it would be too much to reimport the database in question.

**Comment by afg1** [comment]
Tracked this down to GeneCards import having the wrong spelling. Fixed the spelling manually in the database, but I also intend to re-import GeneCards so will keep an eye on this to see if it regresses

**Comment by afg1** [comment]
This is still fixed in the test site, so should be resolved when the release is made
