### ISSUE TITLE
Fix taxonomy & number of species

### ISSUE THREAD

**Issue by afg1** [RNAcentral/rnacentral-import-pipeline#124]
Something is wrong with the way we generate taxonomy trees, and how we calculate the number of species in which an RNA is found.

For example: https://rnacentral.org/rna/URS0000EF28B1/9606

Says it is found in 6 species, but the taxonomy tree shows only human and one single node at the domain level.

Another weird one: https://rnacentral.org/rna/URS0000089FC1/4932

which is showing up in 486 species, which mostly seem to be strains of _S. cerevisiae_ 

This may be a problem in [RNAcentral/rnacentral-webcode](https://github.com/RNAcentral/rnacentral-webcode) rather than the import pipeline

**Comment by blakesweeney** [comment]
This appears to fixed recently.
