### ISSUE TITLE
Update the rnc_secondary_structure_layout_models table

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-import-pipeline#146]
This table contains the information on all r2dt models. It must have an entry for all models in R2DT. There are some cli commands that mostly work to build the data to update them. It may be done as part of the normal pipeline, but should be checked.

**Comment by afg1** [comment]
I think this should be ready to try in the r2dt-rescan branch. I've pipelined everything so I'll need to do #147 and #148 first, and modify the `pipeline_tracking_traveler` table to store r2dt version before I run it
