### ISSUE TITLE
Import linkage to expression atlas

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-import-pipeline#83]
From preliminary work there seem to be several thousand genes we have in common with them. We can import this connection for building links and the like. It would be good to have search terms we can use as well as enough to create links to expression atlas.

**Comment by blakesweeney** [comment]
It is also useful to see what open targets does with the data:

https://platform.opentargets.org/target/ENSG00000251562

I think that is a neat display and worth considering what else we can do.

**Comment by afg1** [comment]
Linkage is imported, but we haven't done anything about the display yet, it's just available as a crossreference.

Should this be closed and work on the display in rna-webcode issue 554?
